### PR TITLE
Add python interactive version of tests/data/eda/01_lxcat_n2_fict.ipynb

### PR DESCRIPTION
**Pull request by gracetangg**
Resolves issue #71 with python interactive code cells compatible with VSCode

### CODE REVIEW

**Comment by padamson** [comment]
Is everything from the `.ipynb` file in the `.py` file? If so, can we just delete the `.ipynb` file?

**Comment by gracetangg** [comment]
@padamson everything has been transferred although it is nice to click on the `.ipynb` file on github and see a preview of a completed run whereas with the `.py` file there is none, and the user would have to run it themselves.

**Comment by padamson** [comment]
Ahh ok, when this issue was created, I don't think GutHub had that feature with notebooks. Now I wonder if the examples should be notebooks and not scripts with interactive code blocks. What do you want think? One or the other or both with duplication?

**Comment by gracetangg** [comment]
@padamson I think that it might be nice to keep the Jupyter Notebooks because of the preview, so if the user doesn't want to run it they can still see the output, but the code cells are nice if they don't want to download Jupyter maybe, so I think to keep both?

**Comment by padamson** [comment]
sounds good, thanks

**Pull request merged**
