### PR TITLE
(WIP) 24-moved-reaction-inside-CS

### PR DESCRIPTION
**Pull request by ndisner**
#Pull Request

##Description
This pull request tackles moving refactor_latex function inside the CS class #24 . LHS and RHS are still separated and not treated as a side yet #34  but that might be fixed in the branch that handles issue #45

### CODE REVIEW

**Comment by padamson** [comment]
Thanks! Changed to WIP until we can update with the `_side` approach.

**Comment by gracetangg** [comment]
I was just reading through some of the changes made on this PR, and I was wondering if we are removing the reaction_latex function?

**Comment by padamson** [comment]
remove the nepc.reaction_latex function and put the functionality into the nepc.CS class

**Comment by padamson** [comment]
Should this PR just be closed? (OBE with #72 ?)

**Pull request closed without merging**
